# Generated by Django 4.1.2 on 2022-10-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('care_of', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14)),
                ('village', models.CharField(max_length=255)),
                ('upazila', models.CharField(max_length=255)),
                ('zila', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pay', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('interest', models.PositiveIntegerField()),
                ('installment_method', models.CharField(choices=[('W', 'Weakly'), ('M', 'Monthly')], default='W', max_length=1)),
                ('installment_pay_day', models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('X', 'Thursday'), ('F', 'Friday'), ('Z', 'Saturday')], default='F', max_length=1)),
                ('total_installment', models.PositiveIntegerField()),
                ('installment_amount', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('order_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.productorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_pay_amount', models.PositiveIntegerField()),
                ('is_pay', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.clientaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.productorder')),
            ],
        ),
    ]
