# Generated by Django 4.1.2 on 2022-10-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientaccount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderitem',
            name='product_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
