# Generated by Django 4.1.2 on 2022-10-23 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_productorderitem_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitem',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='client.clientaccount'),
            preserve_default=False,
        ),
    ]
