# Generated by Django 4.1.2 on 2022-10-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_user'),
        ('client', '0004_productorderitem_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='interest',
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='is_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='client.clientaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientaccount'),
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='product_model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
