# Generated by Django 4.1.2 on 2022-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_productorder_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
