# Generated by Django 4.1.2 on 2022-10-25 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_productorder_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpay',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='installmentpay',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentpay',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentpay',
            name='installment_pay_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='installmentpay',
            name='is_late',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='installmentpay',
            name='is_pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.productorder')),
                ('product_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.productorderitem')),
            ],
        ),
    ]
