# Generated by Django 4.1.2 on 2022-10-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_installmentpay_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientaccount'),
            preserve_default=False,
        ),
    ]
