# Generated by Django 4.1.2 on 2022-10-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='installment_pay_day',
            field=models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='5', max_length=1),
        ),
    ]
