# Generated by Django 4.1.2 on 2022-10-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_productorder_installment_pay_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='installment_pay_day',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default='4', max_length=1),
        ),
    ]
