# Generated by Django 4.1.2 on 2022-10-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_invoice_product_order_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.invoice')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.productorderitem')),
            ],
        ),
    ]
