# Generated by Django 4.1.2 on 2022-10-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_invoicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelist',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
