# Generated by Django 4.1.2 on 2022-10-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_invoicelist_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelist',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
